import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    '../../packages/ui/src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'border-glass': 'rgba(255, 255, 255, 0.12)',
        'tertiary-container': '#b15f00',
        'secondary-fixed-dim': '#c3c6d2',
        'on-error-container': '#93000a',
        'tertiary-fixed-dim': '#ffb77d',
        'primary-fixed': '#85f8c4',
        'on-secondary-container': '#61646e',
        'on-surface-variant': '#3d4a42',
        'on-tertiary-fixed': '#2f1500',
        'on-tertiary': '#ffffff',
        surface: '#f8f9ff',
        'emerald-subtle': '#ECFDF5',
        'surface-dim': '#cbdbf5',
        error: '#ba1a1a',
        'on-background': '#0b1c30',
        'surface-tint': '#006c4a',
        'surface-container': '#e5eeff',
        'on-tertiary-fixed-variant': '#6e3900',
        'surface-container-low': '#eff4ff',
        'emerald-glow': '#10B981',
        'surface-canvas': '#F8FAFC',
        'inverse-primary': '#68dba9',
        'champagne-gold': '#F59E0B',
        'on-secondary-fixed': '#181c24',
        'surface-container-highest': '#d3e4fe',
        background: '#f8f9ff',
        'inverse-on-surface': '#eaf1ff',
        'on-error': '#ffffff',
        'secondary-fixed': '#dfe2ee',
        'inverse-surface': '#213145',
        'surface-card': '#FFFFFF',
        'primary-fixed-dim': '#68dba9',
        'on-secondary-fixed-variant': '#434750',
        'on-tertiary-container': '#fffbff',
        'on-primary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'on-surface': '#0b1c30',
        'surface-variant': '#d3e4fe',
        'on-primary-fixed-variant': '#005137',
        'primary-container': '#00855d',
        'surface-dark-elevated': '#111827',
        'on-secondary': '#ffffff',
        primary: '#006948',
        'on-primary-container': '#f5fff7',
        tertiary: '#8d4b00',
        'surface-bright': '#f8f9ff',
        'surface-container-high': '#dce9ff',
        outline: '#6d7a72',
        'border-hairline': '#E2E8F0',
        'surface-dark': '#0B0F17',
        'tertiary-fixed': '#ffdcc3',
        'outline-variant': '#bccac0',
        secondary: '#5b5e68',
        'champagne-subtle': '#FFFBEB',
        'secondary-container': '#dfe2ee',
        'error-container': '#ffdad6',
        'on-primary-fixed': '#002114',
        brand: {
          50: '#ecfdf5',
          100: '#d1fae5',
          200: '#a7f3d0',
          300: '#6ee7b7',
          400: '#34d399',
          500: '#10b981',
          600: '#059669',
          700: '#047857',
          800: '#065f46',
          900: '#064e3b',
        },
      },
      fontFamily: {
        'display-hero': ['Playfair Display', 'serif'],
        'display-hero-mobile': ['Playfair Display', 'serif'],
        'headline-lg': ['Playfair Display', 'serif'],
        'headline-lg-mobile': ['Playfair Display', 'serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'body-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'label-caps': ['Plus Jakarta Sans', 'sans-serif'],
        'numeric-metric': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'display-hero-mobile': ['34px', { lineHeight: '42px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'label-caps': ['11px', { lineHeight: '14px', letterSpacing: '0.08em', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'numeric-metric': ['28px', { lineHeight: '34px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'body-sm': ['12px', { lineHeight: '18px', fontWeight: '500' }],
        'headline-lg-mobile': ['26px', { lineHeight: '34px', fontWeight: '600' }],
        'display-hero': ['56px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'headline-sm': ['18px', { lineHeight: '26px', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};

export default config;
